// This file is part of Background Music.
//
// Background Music is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation, either version 2 of the
// License, or (at your option) any later version.
//
// Background Music is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Background Music. If not, see <http://www.gnu.org/licenses/>.

//
//  BGMTidal.m
//  BGMApp
//
//  Copyright © 2026 Background Music contributors
//

// Self Include
#import "BGMTidal.h"

// PublicUtility Includes
#import "CADebugMacros.h"

// System Includes
#import <ApplicationServices/ApplicationServices.h>


#pragma clang assume_nonnull begin

// TIDAL's bundle ID. It's an Electron app with no AppleScript dictionary or local API.
static NSString* const kBGMTidalBundleID = @"com.tidal.desktop";

// TIDAL's menus can be localized, so we look for the "Playback" menu by matching its title against a
// list of known titles. Within that menu, the first item is the play/pause toggle regardless of
// locale.
//
// These are functions (rather than file-scope constants) because Objective-C array literals aren't
// compile-time constants.
//
// TODO: These lists only cover a few locales. If you use TIDAL in another language, please add its
//       titles here (or file an issue).
static NSArray<NSString*>* BGMTidalPlaybackMenuTitles(void) {
    return @[
        @"Playback",       // English
        @"Reproducción",   // Spanish
        @"Wiedergabe",     // German
        @"Lecture"         // French
    ];
}

// The play/pause toggle item's title reads as one of these when TIDAL is currently playing (i.e. the
// item would pause playback if pressed).
static NSArray<NSString*>* BGMTidalPauseTitles(void) {
    return @[
        @"Pause",          // English / German / French
        @"Pausa",          // Spanish (Italian)
        @"Pausar"          // Spanish (alternative)
    ];
}

// The play/pause toggle item's title reads as one of these when TIDAL is currently paused (i.e. the
// item would start playback if pressed).
static NSArray<NSString*>* BGMTidalPlayTitles(void) {
    return @[
        @"Play",               // English
        @"Reproducir",         // Spanish
        @"Wiedergabe starten", // German
        @"Lecture"             // French
    ];
}

// The state of TIDAL's playback, as read from the play/pause toggle menu item.
typedef NS_ENUM(NSInteger, BGMTidalPlaybackState) {
    // TIDAL isn't running, we couldn't read the menu, or the title didn't match any known title.
    BGMTidalPlaybackStateUnknown = 0,
    BGMTidalPlaybackStatePlaying,
    BGMTidalPlaybackStatePaused
};

// Read an Accessibility attribute and return its value bridged to an ARC-managed object (or nil if
// the attribute couldn't be read). AXUIElementCopyAttributeValue follows the Create Rule, so we
// hand ownership of the returned value to ARC via CFBridgingRelease.
static id __nullable BGMTidalCopyAXAttribute(AXUIElementRef element, CFStringRef attribute) {
    CFTypeRef value = NULL;
    AXError error = AXUIElementCopyAttributeValue(element, attribute, &value);

    if (error != kAXErrorSuccess || value == NULL) {
        return nil;
    }

    return CFBridgingRelease(value);
}

@implementation BGMTidal

- (instancetype) init {
    // If you're copying this class, replace the ID string with a new one generated by uuidgen (the
    // command line tool).
    if ((self = [super initWithMusicPlayerID:[BGMMusicPlayerBase makeID:@"CA99EB53-26D3-43D6-9716-55AE8FEE1540"]
                                        name:@"TIDAL"
                                    bundleID:kBGMTidalBundleID])) {
    }

    return self;
}

- (void) wasSelected {
    [super wasSelected];

    // Controlling TIDAL's menus requires Background Music to have the Accessibility permission. Ask
    // for it now that the user has actually selected TIDAL (rather than prompting on every launch),
    // mirroring the way the Scripting Bridge players call ensurePermission in wasSelected.
    //
    // AXIsProcessTrustedWithOptions only shows the prompt if the permission hasn't been granted yet.
    // If it isn't granted, all our AX queries fail gracefully and we report TIDAL as not
    // playing/paused.
    NSDictionary* options = @{ (__bridge NSString*)kAXTrustedCheckOptionPrompt: @YES };
    AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)options);
}

// Find TIDAL's play/pause toggle menu item (the first item of its "Playback" menu) and return it as
// an ARC-managed AXUIElementRef, or nil if TIDAL isn't running or the menu couldn't be found.
- (id __nullable) copyPlayPauseMenuItem {
    NSRunningApplication* __nullable app =
        [NSRunningApplication runningApplicationsWithBundleIdentifier:kBGMTidalBundleID].firstObject;

    if (!app) {
        return nil;
    }

    // AXUIElementCreateApplication follows the Create Rule, so we own the returned element.
    AXUIElementRef appElement = AXUIElementCreateApplication(app.processIdentifier);

    id __nullable menuBar = BGMTidalCopyAXAttribute(appElement, kAXMenuBarAttribute);
    CFRelease(appElement);

    if (!menuBar) {
        // Usually because Background Music doesn't have the Accessibility permission yet.
        DebugMsg("BGMTidal::copyPlayPauseMenuItem: Couldn't read TIDAL's menu bar");
        return nil;
    }

    NSArray* __nullable menuBarItems =
        BGMTidalCopyAXAttribute((__bridge AXUIElementRef)menuBar, kAXChildrenAttribute);

    for (id menuBarItemObj in menuBarItems) {
        AXUIElementRef menuBarItem = (__bridge AXUIElementRef)menuBarItemObj;
        NSString* __nullable title = BGMTidalCopyAXAttribute(menuBarItem, kAXTitleAttribute);

        if (!title || ![BGMTidalPlaybackMenuTitles() containsObject:(NSString*)title]) {
            continue;
        }

        // A menu bar item has a single child: the menu it opens.
        NSArray* __nullable menus = BGMTidalCopyAXAttribute(menuBarItem, kAXChildrenAttribute);
        id __nullable menuObj = menus.firstObject;

        if (!menuObj) {
            continue;
        }

        NSArray* __nullable menuItems =
            BGMTidalCopyAXAttribute((__bridge AXUIElementRef)menuObj, kAXChildrenAttribute);

        // The first item of the "Playback" menu is the play/pause toggle.
        return menuItems.firstObject;
    }

    DebugMsg("BGMTidal::copyPlayPauseMenuItem: Couldn't find TIDAL's playback menu");
    return nil;
}

// Read TIDAL's current playback state from the play/pause toggle menu item's title.
- (BGMTidalPlaybackState) playbackState {
    // Don't prompt for the Accessibility permission here (that's done in wasSelected). If it hasn't
    // been granted, the AX queries below just fail and we report the state as unknown.
    if (!AXIsProcessTrusted()) {
        return BGMTidalPlaybackStateUnknown;
    }

    id __nullable menuItem = [self copyPlayPauseMenuItem];

    if (!menuItem) {
        return BGMTidalPlaybackStateUnknown;
    }

    NSString* __nullable title =
        BGMTidalCopyAXAttribute((__bridge AXUIElementRef)menuItem, kAXTitleAttribute);

    if (!title) {
        return BGMTidalPlaybackStateUnknown;
    }

    NSString* titleNN = (NSString*)title;

    if ([BGMTidalPauseTitles() containsObject:titleNN]) {
        // The toggle would pause playback, so TIDAL is currently playing.
        return BGMTidalPlaybackStatePlaying;
    }

    if ([BGMTidalPlayTitles() containsObject:titleNN]) {
        // The toggle would start playback, so TIDAL is currently paused.
        return BGMTidalPlaybackStatePaused;
    }

    DebugMsg("BGMTidal::playbackState: Unrecognized play/pause menu item title");
    return BGMTidalPlaybackStateUnknown;
}

// Press TIDAL's play/pause toggle menu item. Returns YES if the item was found and pressed.
- (BOOL) pressPlayPauseMenuItem {
    id __nullable menuItem = [self copyPlayPauseMenuItem];

    if (!menuItem) {
        return NO;
    }

    AXError error = AXUIElementPerformAction((__bridge AXUIElementRef)menuItem, kAXPressAction);

    if (error != kAXErrorSuccess) {
        DebugMsg("BGMTidal::pressPlayPauseMenuItem: AXUIElementPerformAction failed (%d)", error);
        return NO;
    }

    return YES;
}

- (BOOL) isRunning {
    // Like the other music players, we check with NSRunningApplication rather than launching TIDAL.
    NSArray<NSRunningApplication*>* instances =
        [NSRunningApplication runningApplicationsWithBundleIdentifier:kBGMTidalBundleID];

    return instances.count > 0;
}

- (BOOL) isPlaying {
    return self.playbackState == BGMTidalPlaybackStatePlaying;
}

- (BOOL) isPaused {
    return self.playbackState == BGMTidalPlaybackStatePaused;
}

- (BOOL) pause {
    // isPlaying reads the menu state (which is nil/unknown if TIDAL isn't running), so we don't need
    // to check isRunning here.
    if (!self.playing) {
        return NO;
    }

    DebugMsg("BGMTidal::pause: Pausing TIDAL");
    return [self pressPlayPauseMenuItem];
}

- (BOOL) unpause {
    // isPaused reads the menu state (which is nil/unknown if TIDAL isn't running), so we don't need
    // to check isRunning here.
    if (!self.paused) {
        return NO;
    }

    DebugMsg("BGMTidal::unpause: Unpausing TIDAL");
    return [self pressPlayPauseMenuItem];
}

@end

#pragma clang assume_nonnull end
